services:
  triage-bot:
    build: .
    restart: unless-stopped
    expose:
      - "3325"
    volumes:
      - bot-data:/data
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - KESTRA_CLOUD_URL=${KESTRA_CLOUD_URL}
      - KESTRA_NAMESPACE=${KESTRA_NAMESPACE}
      - KESTRA_TRIAGE_WEBHOOK_KEY=${KESTRA_TRIAGE_WEBHOOK_KEY}
      - KESTRA_ALERT_WEBHOOK_KEY=${KESTRA_ALERT_WEBHOOK_KEY}
      - KESTRA_CONFIG_WEBHOOK_KEY=${KESTRA_CONFIG_WEBHOOK_KEY}
      - GITHUB_APP_URL=${GITHUB_APP_URL}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
      - CALLBACK_PORT=3325

volumes:
  bot-data:

# In case you use a reverse proxy, make sure to connect the bot to the same network as the reverse proxy
networks:
  default:
    external: true
    name: proxy